import { FormEvent, useEffect, useMemo, useState } from 'react'
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup, signOut, updateProfile, type User } from 'firebase/auth'
import { auth, firebaseReady, googleProvider } from './firebase'
import { createCall, createConversation, createStory, ensureUserProfile, findUsers, getUserProfile, saveProfile, sendMessage, watchCalls, watchConversations, watchMessages, watchStories, type CallRecord, type ChatMessage, type Conversation, type Story, type UserProfile } from './services/chat'
import './index.css'
import VoiceCall from './components/VoiceCall'

const starterChats: Conversation[] = [
  { id: 'preview-maya', name: 'Maya Patel', avatar: 'MP', memberIds: [], lastMessage: 'That sounds perfect — see you there!' },
  { id: 'preview-design', name: 'Design Crew', avatar: 'DC', memberIds: [], lastMessage: 'Leo: I added the final screens.' },
  { id: 'preview-jordan', name: 'Jordan Kim', avatar: 'JK', memberIds: [], lastMessage: 'Thanks for sharing that!' },
]
const starterMessages: Record<string, ChatMessage[]> = {
  'preview-maya': [{ id: '1', senderId: 'them', text: 'Are we still on for coffee this afternoon?' }, { id: '2', senderId: 'me', text: 'Absolutely! I’ll be there at 4.' }, { id: '3', senderId: 'them', text: 'That sounds perfect — see you there!' }],
  'preview-design': [{ id: '4', senderId: 'them', text: 'I added the final screens. What do you think?' }],
  'preview-jordan': [{ id: '5', senderId: 'them', text: 'Thanks for sharing that!' }],
}
const initials = (name: string) => name.split(/\s+/).map(x => x[0]).join('').slice(0, 2).toUpperCase() || 'U'
const formatTime = (value?: { toDate?: () => Date } | null) => value?.toDate ? value.toDate().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''

function AuthScreen({ onPreview }: { onPreview: () => void }) {
  const [mode, setMode] = useState<'signin' | 'signup'>('signin'); const [error, setError] = useState('')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!auth) return; setError(''); const data = new FormData(event.currentTarget); try { if (mode === 'signup') { const result = await createUserWithEmailAndPassword(auth, String(data.get('email')), String(data.get('password'))); await updateProfile(result.user, { displayName: String(data.get('name')) }) } else await signInWithEmailAndPassword(auth, String(data.get('email')), String(data.get('password'))) } catch (e) { setError(e instanceof Error ? e.message.replace('Firebase: ', '').replace(/ \(auth\/[^)]+\)\.?$/, '') : 'Unable to sign in.') } }
  const google = async () => { if (!auth) return; setError(''); try { await signInWithPopup(auth, googleProvider) } catch (e) { setError(e instanceof Error ? e.message.replace('Firebase: ', '') : 'Google sign-in failed.') } }
  return <main className="auth"><section className="auth-card"><div className="brand-mark">C</div><h1>Co Chat</h1><p>Chat bright. Feel right.</p>{!firebaseReady ? <><div className="hero-card"><h2>Preview mode</h2><p>Firebase is not configured in this build. Explore the full interface locally, then add your project keys to enable accounts.</p><button className="secondary" onClick={onPreview}>Continue preview</button></div></> : <><div className="auth-tabs"><button className={mode === 'signin' ? 'active' : ''} onClick={() => setMode('signin')}>Sign in</button><button className={mode === 'signup' ? 'active' : ''} onClick={() => setMode('signup')}>Create account</button></div><form onSubmit={submit}>{mode === 'signup' && <label>Display name<input name="name" required placeholder="Your name" /></label>}<label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" minLength={6} required placeholder="At least 6 characters" /></label>{error && <p className="error-text">{error}</p>}<button className="primary">{mode === 'signin' ? 'Sign in' : 'Create account'}</button></form><button className="google-button" onClick={google}>Continue with Google</button><small>Your account syncs securely across devices.</small></>}</section></main>
}
function Nav({ page, setPage }: { page: string; setPage: (value: string) => void }) { return <nav className="bottom-nav">{[['chats', '💬', 'Chats'], ['search', '⌕', 'Search'], ['stories', '◉', 'Status'], ['profile', '☺', 'Profile']].map(([id, icon, label]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><span>{icon}</span>{label}</button>)}</nav> }

function UsernameSetup({ user, onComplete }: { user: User; onComplete: (username: string, displayName: string) => void }) {
  const [username, setUsername] = useState(''); const [displayName, setDisplayName] = useState(user.displayName || ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await saveProfile(user.uid, { displayName, username, notificationsEnabled: true, discoverable: true }); onComplete(username.trim().toLowerCase(), displayName.trim()) } catch (e) { setError(e instanceof Error ? e.message : 'Could not save your profile.') } finally { setSaving(false) } }
  return <main className="auth"><section className="auth-card"><div className="brand-mark">C</div><h1>Set up your profile</h1><p>Choose a unique username so people can find you on Co-Chat.</p><form onSubmit={submit}><label>Display name<input value={displayName} onChange={e => setDisplayName(e.target.value)} placeholder="Your name" required /></label><label>Username<input value={username} onChange={e => setUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase())} placeholder="your_username" minLength={3} maxLength={24} pattern="[a-z0-9_]+" required /></label>{error && <p className="error-text">{error}</p>}<button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Continue'}</button></form></section></main>
}

export default function App() {
  const [user, setUser] = useState<User | null>(null); const [preview, setPreview] = useState(false); const [loading, setLoading] = useState(firebaseReady)
  const [showVoiceCall, setShowVoiceCall] = useState(false); const [page, setPage] = useState('chats'); const [conversations, setConversations] = useState<Conversation[]>(starterChats); const [selected, setSelected] = useState<Conversation | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(''); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [showNew, setShowNew] = useState(false); const [needsUsername, setNeedsUsername] = useState(false); const [senderNames, setSenderNames] = useState<Record<string, string>>({}); const [replyTarget, setReplyTarget] = useState<ChatMessage | null>(null)
  const [stories, setStories] = useState<Story[]>([]); const [activeStory, setActiveStory] = useState<Story | null>(null); const [calls, setCalls] = useState<CallRecord[]>([]); const [storyText, setStoryText] = useState(''); const [profileName, setProfileName] = useState(''); const [profileUsername, setProfileUsername] = useState(''); const [notificationsEnabled, setNotificationsEnabled] = useState(true); const [discoverable, setDiscoverable] = useState(true); const [profileSaved, setProfileSaved] = useState(false); const [darkMode, setDarkMode] = useState(() => localStorage.getItem('cochat-theme') === 'dark')
  const liveUser = preview ? ({ uid: 'preview', displayName: 'Preview user', email: 'preview@cochat.local' } as User) : user
  useEffect(() => { if (!auth) { setLoading(false); return }; return onAuthStateChanged(auth, next => { setUser(next); setLoading(false) }) }, [])
  useEffect(() => { document.documentElement.classList.toggle('dark', darkMode); localStorage.setItem('cochat-theme', darkMode ? 'dark' : 'light') }, [darkMode])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return; const uid = liveUser.uid; ensureUserProfile(uid, { displayName: liveUser.displayName || '', email: liveUser.email || '', photoURL: liveUser.photoURL || '' }).then(() => getUserProfile(uid)).then(profile => { setProfileName(profile?.displayName || liveUser.displayName || ''); setProfileUsername(profile?.username || ''); setNeedsUsername(!localStorage.getItem(`cochat-username-${uid}`)); setNotificationsEnabled(profile?.notificationsEnabled !== false); setDiscoverable(profile?.discoverable !== false) }).catch(() => setError('Could not load your profile.')) }, [liveUser?.uid])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return; const uid = liveUser.uid; return watchConversations(uid, items => setConversations(items)) }, [liveUser?.uid])
  useEffect(() => { if (!selected || selected.id.startsWith('preview-') || !liveUser || liveUser.uid === 'preview') { setMessages(selected ? JSON.parse(localStorage.getItem(`cochat-preview-${selected.id}`) || 'null') || starterMessages[selected.id] || [] : []); return }; return watchMessages(selected.id, setMessages) }, [selected?.id, liveUser?.uid])
  useEffect(() => { if (!liveUser || !messages.length) return; const ids = [...new Set(messages.map(item => item.senderId).filter(id => id !== 'me' && id !== 'them' && id !== liveUser.uid))]; Promise.all(ids.map(async id => { const profile = await getUserProfile(id); return [id, profile?.displayName || profile?.username || id] as const })).then(items => setSenderNames(old => Object.fromEntries([...Object.entries(old), ...items]))) }, [messages, liveUser?.uid])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return watchStories(setStories) }, [liveUser?.uid])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return; const uid = liveUser.uid; return watchCalls(uid, setCalls) }, [liveUser?.uid])
  const visible = useMemo(() => conversations.filter(item => item.name.toLowerCase().includes(search.toLowerCase())), [conversations, search])
  if (loading) return <main className="auth"><section className="auth-card"><div className="brand-mark">C</div><h1>Co Chat</h1><p>Connecting your account…</p></section></main>
  if (!liveUser) return <AuthScreen onPreview={() => setPreview(true)} />
  if (needsUsername && !preview) return <UsernameSetup user={liveUser} onComplete={(username, displayName) => { localStorage.setItem(`cochat-username-${liveUser.uid}`, username); setProfileUsername(username); setProfileName(displayName); setNeedsUsername(false) }} />
  const send = async (event: FormEvent) => { event.preventDefault(); if ((!text.trim() && !selectedFile) || !selected) return; const value = text.trim(); const file = selectedFile; if (value.length > 2000) { setError('Messages must be 2,000 characters or fewer.'); return } setText(''); setSelectedFile(null); const target = replyTarget; setReplyTarget(null); if (selected.id.startsWith('preview-')) { setMessages(old => { const next = [...old, { id: String(Date.now()), senderId: 'me', text: value || file?.name || '', replyTo: target ? { id: target.id, text: target.text, senderId: target.senderId } : null, attachment: file ? { name: file.name, url: URL.createObjectURL(file), type: file.type, size: file.size } : null }]; localStorage.setItem(`cochat-preview-${selected.id}`, JSON.stringify(next)); return next }); return } try { await sendMessage(selected.id, liveUser.uid, value, file || undefined, target) } catch (e) { setError(e instanceof Error ? e.message : 'Message could not be sent. Check your connection.') } }
  const startConversation = async (profile: UserProfile) => { try { const id = await createConversation(liveUser.uid, profile); if (!id) throw new Error('Firebase is not configured.'); setShowNew(false); setSearch(''); setPage('chats'); setSelected({ id, name: profile.displayName, avatar: initials(profile.displayName), memberIds: [liveUser.uid, profile.uid], lastMessage: '' }) } catch (e) { setError(e instanceof Error ? e.message.replace('Firebase: ', '') : 'Could not create that conversation.') } }
  const logout = async () => { try { if (auth && !preview) await signOut(auth); setPreview(false); setUser(null); setSelected(null); setPage('chats') } catch { setError('Could not sign out. Please try again.') } }
  const save = async (event: FormEvent) => { event.preventDefault(); if (preview) return; try { await saveProfile(liveUser.uid, { displayName: profileName, username: profileUsername, notificationsEnabled, discoverable }); await updateProfile(liveUser, { displayName: profileName }); setProfileSaved(true); setError(''); setTimeout(() => setProfileSaved(false), 2000) } catch (e) { setError(e instanceof Error ? e.message : 'Profile could not be saved.') } }
  const call = async (type: 'audio' | 'video') => { if (!selected || preview || selected.memberIds.length < 2) { setError('Sign in and start a conversation with another person to call.'); return }; try { await createCall(selected.memberIds, type); setError(type === 'audio' ? 'Voice call request sent.' : 'Video call request sent.') } catch { setError('Could not create the call request.') } }
  if (selected) return <main className="app chat-screen"><header className="chat-header"><button className="icon" onClick={() => setSelected(null)}>←</button><div className="avatar">{selected.avatar}</div><div><strong>{selected.name}</strong><small>{selected.id.startsWith('preview-') ? 'Preview conversation' : 'Cloud-synced conversation'}</small></div><button className="icon" title="Start audio call" onClick={() => setShowVoiceCall(true)}>☎</button><button className="icon" title="Start video call" onClick={() => call('video')}>▣</button></header>{showVoiceCall && <VoiceCall uid={liveUser.uid} otherUid={selected.memberIds.find(id => id !== liveUser.uid) || ''} otherName={selected.name} onClose={() => setShowVoiceCall(false)} />}<section className="messages">{messages.map(item => { const mine = item.senderId === liveUser.uid || item.senderId === 'me'; const sender = mine ? (profileName || 'You') : (senderNames[item.senderId] || 'Loading…'); return <div className={`bubble ${mine ? 'me' : ''}`} key={item.id}>{item.replyTo && <div className="reply-quote">↪ {item.replyTo.text || 'Attachment'}</div>}{item.attachment && (item.attachment.type.startsWith('image/') ? <img className="message-image" src={item.attachment.url} alt={item.attachment.name} /> : <a className="attachment" href={item.attachment.url} target="_blank" rel="noreferrer">📎 {item.attachment.name}</a>)}{item.text && <span>{item.text}</span>}<small>{formatTime(item.createdAt) || 'now'}{mine ? ' · Delivered' : ''}<button className="reply-button" type="button" onClick={() => setReplyTarget(item)}>Reply</button></small></div>})}</section>{replyTarget && <div className="reply-compose">Replying to: “{replyTarget.text || 'attachment'}”<button type="button" className="icon" onClick={() => setReplyTarget(null)}>×</button></div>}<form className="composer" onSubmit={send}><label className="attach-button" title="Attach a file">📎<input type="file" onChange={e => setSelectedFile(e.target.files?.[0] || null)} /></label><input value={text} onChange={e => setText(e.target.value)} placeholder={selectedFile ? selectedFile.name : 'Write a message'} /><button className="primary">Send</button></form></main>
  return <main className="app"><header className="topbar"><div><div className="eyebrow">WELCOME BACK</div><h1>{page === 'chats' ? 'Messages' : page[0].toUpperCase() + page.slice(1)}</h1></div><button className="avatar profile-button" onClick={() => setPage('profile')}>{initials(liveUser.displayName || liveUser.email || 'U')}</button></header><section className="content">{error && <div className="notice">{error}<button className="icon" onClick={() => setError('')}>×</button></div>}
    {page === 'chats' && <><input className="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your conversations" /><div className="section-title">RECENT CONVERSATIONS</div><div className="list">{visible.map(item => <button className="chat-row" key={item.id} onClick={() => setSelected(item)}><span className="avatar">{item.avatar}</span><span className="chat-copy"><strong>{item.name}</strong><span>{item.lastMessage || 'Start a conversation'}</span></span><small>{formatTime(item.lastMessageAt) || ' '}</small></button>)}{!visible.length && <div className="empty-state">No conversations found.</div>}</div>{showNew && <NewConversation uid={liveUser.uid} onSelect={startConversation} onClose={() => setShowNew(false)} />}</>}
    {page === 'search' && <SearchPanel uid={liveUser.uid} onSelect={startConversation} />}
    {page === 'status' && <div className="hero-card coming-soon"><span>◉</span><h2>Stories are coming soon</h2><p>We’re focusing today’s release on fast, reliable conversations. Stories will follow in a future release.</p></div>}
    {page === 'profile' && <><form className="profile-card" onSubmit={save}><div className="avatar large">{initials(profileName || liveUser.email || 'U')}</div><h2>{profileName || 'Co Chat member'}</h2><p>{liveUser.email}</p><label className="field-label">Display name<input value={profileName} onChange={e => setProfileName(e.target.value)} required /></label><label className="field-label">Username<input value={profileUsername} onChange={e => setProfileUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase())} minLength={3} maxLength={24} pattern="[a-z0-9_]+" required /><small>Unique, 3–24 characters: letters, numbers, and underscores.</small></label><button className="primary" disabled={preview}>{profileSaved ? 'Saved ✓' : 'Save profile'}</button></form><div className="settings"><button type="button" onClick={() => setNotificationsEnabled(value => !value)}>🔔 Notifications <span>{notificationsEnabled ? 'On' : 'Off'}</span></button><button type="button" onClick={() => setDarkMode(value => !value)}>◐ Appearance <span>{darkMode ? 'Dark' : 'Light'}</span></button><button type="button" onClick={() => setDiscoverable(value => !value)}>🔒 Discoverable in search <span>{discoverable ? 'On' : 'Off'}</span></button><button type="button" onClick={logout}>↪ Log out <span>›</span></button></div></>}
  </section><Nav page={page} setPage={setPage} /></main>
}

function SearchPanel({ uid, onSelect }: { uid: string; onSelect: (profile: UserProfile) => void }) {
  const [term, setTerm] = useState('')
  const [history, setHistory] = useState<string[]>(() => JSON.parse(localStorage.getItem(`cochat-search-history-${uid}`) || '[]'))
  const [results, setResults] = useState<UserProfile[]>([])
  useEffect(() => { const timer = setTimeout(() => { if (term.trim()) findUsers(term, uid).then(setResults).catch(() => setResults([])); else setResults([]) }, 250); return () => clearTimeout(timer) }, [term, uid])
  const remember = (value: string) => { const next = [value.toLowerCase(), ...history.filter(item => item !== value.toLowerCase())].slice(0, 8); setHistory(next); localStorage.setItem(`cochat-search-history-${uid}`, JSON.stringify(next)) }
  return <section className="search-panel"><p className="eyebrow">FIND PEOPLE</p><h2>Search Co‑Chat</h2><input autoFocus value={term} onChange={e => setTerm(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && term.trim()) remember(term.trim()) }} placeholder="Search by username" />{history.length > 0 && <div className="search-history"><div className="section-title">RECENT SEARCHES <button className="icon" type="button" onClick={() => { setHistory([]); localStorage.removeItem(`cochat-search-history-${uid}`) }}>Clear</button></div>{history.map(item => <button className="secondary" type="button" key={item} onClick={() => setTerm(item)}>@{item}</button>)}</div>}<div className="list">{results.map(profile => <div className="person-result" key={profile.uid}><span className="avatar">{initials(profile.displayName)}</span><span className="chat-copy"><strong>{profile.displayName}</strong><span>@{profile.username}</span></span><button className="secondary compact" type="button" onClick={() => { remember(profile.username); onSelect(profile) }}>Message</button></div>)}{term && !results.length && <div className="empty-state">No matching people yet.</div>}</div></section>
}

function NewConversation({ uid, onSelect, onClose }: { uid: string; onSelect: (profile: UserProfile) => void; onClose: () => void }) {
  const [term, setTerm] = useState(''); const [results, setResults] = useState<UserProfile[]>([]); const [focused, setFocused] = useState<UserProfile | null>(null)
  useEffect(() => { const timer = setTimeout(() => { if (term.trim()) findUsers(term, uid).then(setResults).catch(() => setResults([])); else setResults([]) }, 250); return () => clearTimeout(timer) }, [term, uid])
  return <div className="modal-backdrop"><section className="modal"><header><div><p className="eyebrow">FIND PEOPLE</p><h2>New conversation</h2></div><button className="icon" onClick={onClose}>×</button></header><input autoFocus value={term} onChange={e => setTerm(e.target.value)} placeholder="Search by username" /><div className="list">{results.map(profile => <div className="person-result" key={profile.uid}><span className="avatar">{initials(profile.displayName)}</span><span className="chat-copy"><strong>{profile.displayName}</strong><span>@{profile.username}</span></span><button className="secondary compact" onClick={() => onSelect(profile)}>Message</button><button className="icon" title="View profile" onClick={() => setFocused(profile)}>⋯</button></div>)}{term && !results.length && <div className="empty-state">No matching people yet.</div>}</div>{focused && <div className="person-profile"><button className="icon close-profile" onClick={() => setFocused(null)}>×</button><div className="avatar large">{initials(focused.displayName)}</div><h3>{focused.displayName}</h3><p>@{focused.username}</p><small>Discoverable on Co-Chat</small><button className="primary" onClick={() => onSelect(focused)}>Message {focused.displayName.split(' ')[0]}</button></div>}</section></div>
}
