import { FormEvent, useEffect, useMemo, useState } from 'react'
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup, signOut, updateProfile, type User } from 'firebase/auth'
import { auth, firebaseReady, googleProvider } from './firebase'
import { createCall, createConversation, createStory, ensureUserProfile, findUsers, saveProfile, sendMessage, watchCalls, watchConversations, watchMessages, watchStories, type CallRecord, type ChatMessage, type Conversation, type Story, type UserProfile } from './services/chat'
import './index.css'

const starterChats: Conversation[] = [
  { id: 'preview-maya', name: 'Maya Patel', avatar: 'MP', memberIds: [], lastMessage: 'That sounds perfect — see you there!' },
  { id: 'preview-design', name: 'Design Crew', avatar: 'DC', memberIds: [], lastMessage: 'Leo: I added the final screens.' },
  { id: 'preview-jordan', name: 'Jordan Kim', avatar: 'JK', memberIds: [], lastMessage: 'Thanks for sharing that!' },
]
const starterMessages: Record<string, ChatMessage[]> = {
  'preview-maya': [{ id: '1', senderId: 'them', text: 'Are we still on for coffee this afternoon?' }, { id: '2', senderId: 'me', text: 'Absolutely! I’ll be there at 4.' }, { id: '3', senderId: 'them', text: 'That sounds perfect — see you there!' }],
  'preview-design': [{ id: '4', senderId: 'them', text: 'I added the final screens. What do you think?' }],
  'preview-jordan': [{ id: '5', senderId: 'them', text: 'Thanks for sharing that!' }],
}
const initials = (name: string) => name.split(/\s+/).map(x => x[0]).join('').slice(0, 2).toUpperCase() || 'U'
const formatTime = (value?: { toDate?: () => Date } | null) => value?.toDate ? value.toDate().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''

function AuthScreen({ onPreview }: { onPreview: () => void }) {
  const [mode, setMode] = useState<'signin' | 'signup'>('signin'); const [error, setError] = useState('')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!auth) return; setError(''); const data = new FormData(event.currentTarget); try { if (mode === 'signup') { const result = await createUserWithEmailAndPassword(auth, String(data.get('email')), String(data.get('password'))); await updateProfile(result.user, { displayName: String(data.get('name')) }) } else await signInWithEmailAndPassword(auth, String(data.get('email')), String(data.get('password'))) } catch (e) { setError(e instanceof Error ? e.message.replace('Firebase: ', '').replace(/ \(auth\/[^)]+\)\.?$/, '') : 'Unable to sign in.') } }
  const google = async () => { if (!auth) return; setError(''); try { await signInWithPopup(auth, googleProvider) } catch (e) { setError(e instanceof Error ? e.message.replace('Firebase: ', '') : 'Google sign-in failed.') } }
  return <main className="auth"><section className="auth-card"><div className="brand-mark">C</div><h1>Co Chat</h1><p>Chat bright. Feel right.</p>{!firebaseReady ? <><div className="hero-card"><h2>Preview mode</h2><p>Firebase is not configured in this build. Explore the full interface locally, then add your project keys to enable accounts.</p><button className="secondary" onClick={onPreview}>Continue preview</button></div></> : <><div className="auth-tabs"><button className={mode === 'signin' ? 'active' : ''} onClick={() => setMode('signin')}>Sign in</button><button className={mode === 'signup' ? 'active' : ''} onClick={() => setMode('signup')}>Create account</button></div><form onSubmit={submit}>{mode === 'signup' && <label>Display name<input name="name" required placeholder="Your name" /></label>}<label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" minLength={6} required placeholder="At least 6 characters" /></label>{error && <p className="error-text">{error}</p>}<button className="primary">{mode === 'signin' ? 'Sign in' : 'Create account'}</button></form><button className="google-button" onClick={google}>Continue with Google</button><small>Your account syncs securely across devices.</small></>}</section></main>
}
function Nav({ page, setPage }: { page: string; setPage: (value: string) => void }) { return <nav className="bottom-nav">{[['chats', '💬', 'Chats'], ['calls', '📞', 'Calls'], ['stories', '◉', 'Stories'], ['profile', '☺', 'Profile']].map(([id, icon, label]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><span>{icon}</span>{label}</button>)}</nav> }

export default function App() {
  const [user, setUser] = useState<User | null>(null); const [preview, setPreview] = useState(false); const [loading, setLoading] = useState(firebaseReady)
  const [page, setPage] = useState('chats'); const [conversations, setConversations] = useState<Conversation[]>(starterChats); const [selected, setSelected] = useState<Conversation | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(''); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [showNew, setShowNew] = useState(false)
  const [stories, setStories] = useState<Story[]>([]); const [activeStory, setActiveStory] = useState<Story | null>(null); const [calls, setCalls] = useState<CallRecord[]>([]); const [storyText, setStoryText] = useState(''); const [profileName, setProfileName] = useState(''); const [profileUsername, setProfileUsername] = useState(''); const [notificationsEnabled, setNotificationsEnabled] = useState(true); const [discoverable, setDiscoverable] = useState(true); const [profileSaved, setProfileSaved] = useState(false)
  const liveUser = preview ? ({ uid: 'preview', displayName: 'Preview user', email: 'preview@cochat.local' } as User) : user
  useEffect(() => { if (!auth) { setLoading(false); return }; return onAuthStateChanged(auth, next => { setUser(next); setLoading(false) }) }, [])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return; ensureUserProfile(liveUser.uid, { displayName: liveUser.displayName || '', email: liveUser.email || '', photoURL: liveUser.photoURL || '' }).catch(() => setError('Could not load your profile.')); setProfileName(liveUser.displayName || ''); setProfileUsername((liveUser.displayName || liveUser.email?.split('@')[0] || '').toLowerCase().replace(/[^a-z0-9]/g, '')) }, [liveUser?.uid])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return; const uid = liveUser.uid; return watchConversations(uid, items => setConversations(items)) }, [liveUser?.uid])
  useEffect(() => { if (!selected || selected.id.startsWith('preview-') || !liveUser || liveUser.uid === 'preview') { setMessages(selected ? starterMessages[selected.id] || [] : []); return }; return watchMessages(selected.id, setMessages) }, [selected?.id, liveUser?.uid])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return watchStories(setStories) }, [liveUser?.uid])
  useEffect(() => { if (!liveUser || liveUser.uid === 'preview') return; const uid = liveUser.uid; return watchCalls(uid, setCalls) }, [liveUser?.uid])
  const visible = useMemo(() => conversations.filter(item => item.name.toLowerCase().includes(search.toLowerCase())), [conversations, search])
  if (loading) return <main className="auth"><section className="auth-card"><div className="brand-mark">C</div><h1>Co Chat</h1><p>Connecting your account…</p></section></main>
  if (!liveUser) return <AuthScreen onPreview={() => setPreview(true)} />
  const send = async (event: FormEvent) => { event.preventDefault(); if ((!text.trim() && !selectedFile) || !selected) return; const value = text.trim(); const file = selectedFile; if (value.length > 2000) { setError('Messages must be 2,000 characters or fewer.'); return } setText(''); setSelectedFile(null); if (selected.id.startsWith('preview-')) { setMessages(old => [...old, { id: String(Date.now()), senderId: 'me', text: value || file?.name || '', attachment: file ? { name: file.name, url: URL.createObjectURL(file), type: file.type, size: file.size } : null }]); return } try { await sendMessage(selected.id, liveUser.uid, value, file || undefined) } catch (e) { setError(e instanceof Error ? e.message : 'Message could not be sent. Check your connection.') } }
  const startConversation = async (profile: UserProfile) => { try { const id = await createConversation(liveUser.uid, profile); setShowNew(false); setSearch(''); setPage('chats'); setSelected({ id, name: profile.displayName, avatar: initials(profile.displayName), memberIds: [liveUser.uid, profile.uid], lastMessage: '' }) } catch { setError('Could not create that conversation.') } }
  const save = async (event: FormEvent) => { event.preventDefault(); if (preview) return; try { await saveProfile(liveUser.uid, { displayName: profileName, username: profileUsername, notificationsEnabled, discoverable }); await updateProfile(liveUser, { displayName: profileName }); setProfileSaved(true); setTimeout(() => setProfileSaved(false), 2000) } catch { setError('Profile could not be saved.') } }
  const call = async (type: 'audio' | 'video') => { if (!selected || preview || selected.memberIds.length < 2) { setError('Sign in and start a conversation with another person to call.'); return }; try { await createCall(selected.memberIds, type); setSelected(null); setPage('calls') } catch { setError('Could not create the call request.') } }
  if (selected) return <main className="app"><header className="chat-header"><button className="icon" onClick={() => setSelected(null)}>←</button><div className="avatar">{selected.avatar}</div><div><strong>{selected.name}</strong><small>{selected.id.startsWith('preview-') ? 'Preview conversation' : 'Cloud-synced conversation'}</small></div><button className="icon" title="Start audio call" onClick={() => call('audio')}>☎</button><button className="icon" title="Start video call" onClick={() => call('video')}>▣</button></header><section className="messages">{messages.map(item => <div className={`bubble ${item.senderId === liveUser.uid || item.senderId === 'me' ? 'me' : ''}`} key={item.id}>{item.attachment && (item.attachment.type.startsWith('image/') ? <img className="message-image" src={item.attachment.url} alt={item.attachment.name} /> : <a className="attachment" href={item.attachment.url} target="_blank" rel="noreferrer">📎 {item.attachment.name}</a>)}{item.text && <span>{item.text}</span>}<small>{formatTime(item.createdAt) || 'now'}</small></div>)}</section><form className="composer" onSubmit={send}><label className="attach-button" title="Attach a file">📎<input type="file" onChange={e => setSelectedFile(e.target.files?.[0] || null)} /></label><input value={text} onChange={e => setText(e.target.value)} placeholder={selectedFile ? selectedFile.name : 'Write a message'} /><button className="primary">Send</button></form></main>
  return <main className="app"><header className="topbar"><div><div className="eyebrow">WELCOME BACK</div><h1>{page === 'chats' ? 'Messages' : page[0].toUpperCase() + page.slice(1)}</h1></div><button className="avatar profile-button" onClick={() => setPage('profile')}>{initials(liveUser.displayName || liveUser.email || 'U')}</button></header><section className="content">{error && <div className="notice">{error}<button className="icon" onClick={() => setError('')}>×</button></div>}
    {page === 'chats' && <><input className="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your conversations" /><div className="section-title">RECENT CONVERSATIONS</div><div className="list">{visible.map(item => <button className="chat-row" key={item.id} onClick={() => setSelected(item)}><span className="avatar">{item.avatar}</span><span className="chat-copy"><strong>{item.name}</strong><span>{item.lastMessage || 'Start a conversation'}</span></span><small>{formatTime(item.lastMessageAt) || ' '}</small></button>)}{!visible.length && <div className="empty-state">No conversations found.</div>}</div><button className="fab" onClick={() => setShowNew(true)} aria-label="New conversation">＋</button>{showNew && <NewConversation uid={liveUser.uid} onSelect={startConversation} onClose={() => setShowNew(false)} />}</>}
    {page === 'calls' && <><div className="hero-card"><span>📞</span><h2>Call history</h2><p>Call requests are saved securely. Live audio and video rooms will use the same conversation membership when WebRTC signaling is added.</p></div><div className="section-title">RECENT</div><div className="activity-list">{calls.map(item => <div className="activity" key={item.id}>{item.type === 'video' ? '▣' : '☎'} <span>{item.type} call · {item.status} · {formatTime(item.createdAt) || 'just now'}</span></div>)}{!calls.length && <div className="empty-state">No calls yet.</div>}</div></>}
    {page === 'stories' && <><div className="story-grid"><button className="story mine" onClick={() => document.getElementById('story-box')?.focus()}><b>＋</b><span>Your story</span></button>{stories.map((story, i) => <button className="story" key={story.id} onClick={() => setActiveStory(story)}><div className={`story-art a${i % 3}`}>{initials(story.displayName)[0]}</div><span>{story.displayName}</span></button>)}</div><form className="hero-card" onSubmit={async e => { e.preventDefault(); const value = storyText.trim(); if (!value || value.length > 500 || preview) return; try { await createStory(liveUser.uid, liveUser.displayName || 'Co-Chat member', value); setStoryText('') } catch { setError('Story could not be published.') } }}><span>◉</span><h2>Share a moment</h2><p>Stories disappear automatically after 24 hours.</p><textarea id="story-box" value={storyText} onChange={e => setStoryText(e.target.value)} maxLength={500} placeholder={preview ? 'Sign in to publish stories' : 'What are you thinking?'} disabled={preview} /><button className="primary" disabled={preview || !storyText.trim()}>Publish story</button></form>{activeStory && <div className="modal-backdrop" onClick={() => setActiveStory(null)}><section className="story-viewer" onClick={e => e.stopPropagation()}><button className="icon" onClick={() => setActiveStory(null)}>×</button><div className="story-art">{initials(activeStory.displayName)[0]}</div><h2>{activeStory.displayName}</h2><p>{activeStory.text}</p><small>Disappears after 24 hours</small></section></div>}</>}
    {page === 'profile' && <><form className="profile-card" onSubmit={save}><div className="avatar large">{initials(profileName || liveUser.email || 'U')}</div><h2>{profileName || 'Co Chat member'}</h2><p>{liveUser.email}</p><label className="field-label">Display name<input value={profileName} onChange={e => setProfileName(e.target.value)} required /></label><label className="field-label">Username<input value={profileUsername} onChange={e => setProfileUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase())} required /></label><button className="primary" disabled={preview}>{profileSaved ? 'Saved ✓' : 'Save profile'}</button></form><div className="settings"><button type="button" onClick={() => setNotificationsEnabled(value => !value)}>🔔 Notifications <span>{notificationsEnabled ? 'On' : 'Off'}</span></button><button type="button">◐ Appearance <span>Light</span></button><button type="button" onClick={() => setDiscoverable(value => !value)}>🔒 Discoverable in search <span>{discoverable ? 'On' : 'Off'}</span></button><button type="button" onClick={() => { if (auth && !preview) signOut(auth); else { setPreview(false); setUser(null) } }}>↪ Sign out <span>›</span></button></div></>}
  </section><Nav page={page} setPage={setPage} /></main>
}

function NewConversation({ uid, onSelect, onClose }: { uid: string; onSelect: (profile: UserProfile) => void; onClose: () => void }) { const [term, setTerm] = useState(''); const [results, setResults] = useState<UserProfile[]>([]); useEffect(() => { const timer = setTimeout(() => { if (term.trim()) findUsers(term, uid).then(setResults).catch(() => setResults([])) }, 250); return () => clearTimeout(timer) }, [term, uid]); return <div className="modal-backdrop"><section className="modal"><header><h2>New conversation</h2><button className="icon" onClick={onClose}>×</button></header><input autoFocus value={term} onChange={e => setTerm(e.target.value)} placeholder="Search by username" /><div className="list">{results.map(profile => <button className="chat-row" key={profile.uid} onClick={() => onSelect(profile)}><span className="avatar">{initials(profile.displayName)}</span><span className="chat-copy"><strong>{profile.displayName}</strong><span>@{profile.username}</span></span></button>)}{term && !results.length && <div className="empty-state">No matching people yet.</div>}</div></section></div> }
